#!/usr/bin/perl
#
#	ut_xrtcentroid_pc
#
# Changes:
#           0.1.0 - 04/08/2004 - CS First working version
#           0.1.1 - 05/08/2004 - BS Adapted for xrtcentroid task
#           0.1.2 - 31/08/2004 - BS Added calcpos parameter
#           0.1.3 - 11/01/2005 - BS Deleted 'caldbdir' input parameter
#
#

use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrtcentroid",
			    utname  => "ut_xrtcentroid_pc",	   
			    version => "0.1.3",
			    );
    
# Set Parameter
    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");

# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");
    
    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;

    my $ArchDir="ut_xrtcentroid";

# Input Files Check
    my @chk_inp = ("$input/$ArchDir/sw00073232001xpcwnpocl.evt.gz");
 
    $ut->checkExist("Input",@chk_inp)
        if $ut->isValid;

# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrtcentroid_pc_xpcwnpocl.txt",
                    "$input/$ArchDir/ut_xrtcentroid_pc_xpcwnpocltmp.fits"
		    );
    $ut->checkExist("Prototype",@chk_proto)
        if $ut->isValid;

# Executables Files Check
   my @chk_exe = ("xrtcentroid","ftdiff","fverify", "fselect", "fstatistic");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;

# Task Files Check
    my %par_task = (
		    infile        => "$input/$ArchDir/sw00073232001xpcwnpocl.evt.gz",
		    outfile       => "DEFAULT",
		    outdir        => "$output",
		    posfile       => "CALDB",
		    interactive   => "no",
		    boxra         => 180.1,
		    boxdec        => 89.1,
		    boxradius     => 2,
		    hist          => "no",
		    deriv         => "no",
		    clobber       => "yes",
		    chatter       => $chat,
		    cleanup       => "yes",
                    calcpos       => "yes",
		    );
    $ut->runTask(%par_task)
        if $ut->isValid;

# diff
   if ($ut->isValid)
   {
       $ut->diff("$output/sw00073232001xpcwnpocl.txt",
		 "$input/$ArchDir/ut_xrtcentroid_pc_xpcwnpocl.txt");
       

   }
   $ut->delete();
}
