# Component (mission) name. Developers need not change/delete this.
HD_COMPONENT_NAME	= swift

# Software release version number. Developers need not change/delete this.
HD_COMPONENT_VERS	=

# Subdirectories of the current directory (or from the top package-level)
# to be built.
HD_SUBDIRS		= xrtcalcpi xrtflagpix xrtpcgrade xrtpipeline xrttools xrttimetag xrtmkarf xrtscreen xrtfilter xrtevtrec xrtimage xrtpdcorr xrtproducts xrthkproc xrttam xrttdrss xrthotpix xrtcentroid xrtwtcorr xrtexpomap xrtinstrmap xrtexpocalc xrtexpocorr xrtlccorr xrttdrss2 xrtpccorr xrtpcbias xrtgrblc xrtgrblcspec xrtphascorr


# Subdirectories of the current directory (or from the top package-level)
# which contain one or more unit test targets.
HD_TEST_SUBDIRS         = xrtcalcpi xrtflagpix xrtpcgrade xrtpipeline xrttools xrttimetag xrtmkarf xrtscreen xrtfilter xrtevtrec xrtimage xrtpdcorr xrtproducts xrthkproc xrttam xrttdrss xrthotpix xrtcentroid xrtwtcorr xrtexpomap xrtlccorr xrttdrss2 xrtpccorr xrtgrblc xrtgrblcspec xrtphascorr

HD_TEST_PERL_SCRIPTS    = ut_xrtALL

include ${HD_STD_MAKEFILE}
