#!/usr/bin/perl
#
#  ut_xrtimage
#
#
#
# Changes:
#           0.1.0 - 04/08/2004 - CS First working version
#           0.1.1 - 05/08/2004 - BS Adapted for xrtimage task
#           0.1.2 - 06/10/2004 - FT Changed badpix onboardbp and region 
#                                   CALDB file name
#           0.1.3 - 13/01/2005 - BS Deleted 'caldbdir' input parameter
#           0.1.4 - 17/06/2005 - BS Added 'hdfile' and 'biasdiff' new input 
#                                   parameters 
#           0.1.5 - 23/06/2005 - BS Added 'maxtemp' new input parameter
use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrtimage",
			    utname  => "ut_xrtimage",
			    version => "0.1.5",
			    );
    
# Set Parameter
    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");

# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_xrtimage";
    
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/sw00132247000xim_rw.img.gz", "$input/$ArchDir/sw00132247000xhd.hk.gz"
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrtimageximrw.img","$input/$ArchDir/ut_xrtimageximrwbp.fits"
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("xrtimage","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;
# Task Files Check
    my %par_task = (

		    infile     => "$input/$ArchDir/sw00132247000xim_rw.img.gz",
		    outfile    => "$output/sw00132247000xim_rw.img",
		    hdfile     => "$input/$ArchDir/sw00132247000xhd.hk.gz",
		    biasfile   => "CALDB",
                    bias       => -40.,
                    biasdiff   =>  20,
		    maxtemp    => -55,
                    cleanbp    => "yes",
                    cleansrc   => "yes",
                    subbias    => "yes",
                    gtiscreen  => "no",
                    gtifile    => "NONE",
		    bpfile     => "CALDB",
                    srcfile    => "CALDB",
                    userbpfile => "NONE",
		    bptable    => "CALDB",
		    outbpfile  => "DEFAULT",
		    chatter    => $chat,
		    clobber    => "$clobber",
		    history    => "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/sw00132247000xim_rw.img");
	$ut->fverify("$output/sw00132247000xim_rwbp.fits");
	
	
# ftdiff
	$ut->ftdiff("$output/sw00132247000xim_rw.img",
		    "$input/$ArchDir/ut_xrtimageximrw.img");

	$ut->ftdiff("$output/sw00132247000xim_rwbp.fits",
		    "$input/$ArchDir/ut_xrtimageximrwbp.fits");
    }    
    
    $ut->delete();
}
