# Component (mission) name. Developers need not change/delete this.
HD_COMPONENT_NAME	= swift

# Software release version number. Developers need not change/delete this.
HD_COMPONENT_VERS	=

# Perl script(s) to install.
HD_INSTALL_PERL_SCRIPTS	= xrtproducts

# Help file(s) to install.
HD_INSTALL_HELP		= xrtproducts.html

# Parameter file(s) to install.
HD_INSTALL_PFILES	= xrtproducts.par
HD_TEST_PERL_SCRIPTS	= ut_${HD_INSTALL_PERL_SCRIPTS}_wt ut_${HD_INSTALL_PERL_SCRIPTS}_pc ut_${HD_INSTALL_PERL_SCRIPTS}_lr
include ${HD_STD_MAKEFILE}
