#!/usr/bin/perl
#
#  ut_xrtproducts_pc
#
#
#
# Changes:
#           0.1.0 - 04/08/2004 - CS First working version
#           0.1.1 - 05/08/2004 - MC Modified for this task
#           0.1.2 - 11/08/2004 - BS Bug fixed
#           0.1.3 - 13/01/2005 - BS Deleted 'caldbdir' input parameter
#           0.1.4 - 10/02/2005 - BS Deleted 'srcdetx/y' input pars
#           0.1.5 - 16/02/2005 - BS Added 'inarffile' input parameter
#           0.1.6 - 24/03/2005 - BS replaced xspec with xspec11
#           0.1.7 - 24/03/2005 - BS Deleted 'ra' and 'dec' input pars
#           0.1.8 - 19/10/2005 -    Added 'expofile' input parameter
#           0.1.9 - 28/10/2005 -    Modified exposure map file name
#           0.2.0 - 10/03/2006 -    Modified input dataset    
#           0.2.1 - 21/07/2009 - NS Replaced xspec11 with xspec
#           0.2.2 - 01/07/2010 - NS Added 'extended' and 'arfboxsize' input parameters
#           0.2.3 - 08/06/2014 - NS Added new input parameters needed for background products extraction
#                                   Added 'correctlc' input parameter

use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrtproducts",
			    utname    => "ut_xrtproducts_pc", 
			    version => "0.2.3",
			    );
    
# Set Parameter
    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir")."/".$ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");


# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    

    my $headas=$ENV{'HEADAS'};
    my $ArchDir="ut_xrtproducts";
    
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/sw00192059991xpcw2po_cl.evt.gz",
		   "$input/$ArchDir/sw00192059991xpcw2po_ex.img.gz",
		   "$input/$ArchDir/sw00192059991xpcw2po_cl_bkg.reg",
		   "$input/$ArchDir/sw00192059991xpcw2po_cl.reg");

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrtproducts_pc.pha",
                    "$input/$ArchDir/ut_xrtproducts_pc.lc",
                    "$input/$ArchDir/ut_xrtproducts_pc.img",
		    "$input/$ArchDir/ut_xrtproducts_pc.arf"
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("xrtproducts","fstatistic","xrtmkarf","xspec","lcurve",
		   "xselect","ximage","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;
# Task Files Check
    my %par_task = (
		    infile     => "$input/$ArchDir/sw00192059991xpcw2po_cl.evt.gz",
		    regionfile => "$input/$ArchDir/sw00192059991xpcw2po_cl.reg",
                    bkgextract => "yes",
		    bkgregionfile => "$input/$ArchDir/sw00192059991xpcw2po_cl_bkg.reg",
		    expofile   => "$input/$ArchDir/sw00192059991xpcw2po_ex.img.gz",
		    outdir     => "$output",
		    stemout    => "DEFAULT",
                    binsize    => 2.51,
                    display    => "no",
                    lcfile     => "DEFAULT",
		    phafile    => "DEFAULT",
                    bkglcfile  => "DEFAULT",
		    bkgphafile => "DEFAULT",
                    imagefile  => "DEFAULT",
		    gtifile    => "NONE",
                    arffile    => "DEFAULT",
                    rmffile    => "CALDB",
                    inarffile  => "CALDB",
                    mirfile    => "CALDB",
                    transmfile => "CALDB",
		    psffile    => "CALDB",
		    vigfile    => "CALDB",
		    psfflag    => "yes",
		    extended   => "no",
		    arfboxsize => 10,
		    plotdevice => "gif",
		    pilow      => 20,
		    pihigh     => 1000,
		    correctlc  => "no",
		    clobber    => "$clobber",
		    chatter    => $chat,
		    history    => "yes",
		    cleanup    => "yes",
		    );



    $ut->runTask(%par_task)
	if $ut->isValid;
    
# fverify
    if ($ut->isValid) {
	$ut->fverify("$output/sw00192059991xpcw2posr.pha");
	$ut->fverify("$output/sw00192059991xpcw2posr.lc");
	$ut->fverify("$output/sw00192059991xpcw2pobkg.pha");
	$ut->fverify("$output/sw00192059991xpcw2pobkg.lc");
	$ut->fverify("$output/sw00192059991xpcw2po_sk.img");
	$ut->fverify("$output/sw00192059991xpcw2posr.arf");
	
	
# ftdiff
	$ut->ftdiff("$output/sw00192059991xpcw2posr.pha",
		    "$input/$ArchDir/ut_xrtproducts_pc.pha");
	$ut->ftdiff("$output/sw00192059991xpcw2posr.lc",
		    "$input/$ArchDir/ut_xrtproducts_pc.lc");
	$ut->ftdiff("$output/sw00192059991xpcw2pobkg.pha",
		    "$input/$ArchDir/ut_xrtproducts_pc_bkg.pha");
	$ut->ftdiff("$output/sw00192059991xpcw2pobkg.lc",
		    "$input/$ArchDir/ut_xrtproducts_pc_bkg.lc");
	$ut->ftdiff("$output/sw00192059991xpcw2po_sk.img",
		    "$input/$ArchDir/ut_xrtproducts_pc.img");
	$ut->ftdiff("$output/sw00192059991xpcw2posr.arf",
		    "$input/$ArchDir/ut_xrtproducts_pc.arf");
	
    }   
    $ut->delete();
}
