#!/usr/bin/perl
#
#  ut_xrtpdcorr_pu
#
#
#
# Changes:
#           0.1.0 - 04/08/2004 - CS First working version
#           0.1.1 - 05/08/2004 - BS Adapted for xrtpdcorr task
#           0.1.2 - 13/01/2005 - BS Deleted 'caldbdir' input parameter
#           0.1.3 - 28/06/2005 - BS Added 'biasdiff' and 'hdfile' input 
#                                   parameters
#           0.1.4 - 10/07/2007 - NS Added 'thrfile' input parameter

use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrtpdcorr",
			    utname  => "ut_xrtpdcorr_pu",
			    version => "0.1.4",
			    );
    
# Set Parameter
    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");


# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_xrtpdcorr";
    
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/sw00030025001xpub1po_uf.evt.gz","$input/$ArchDir/sw00030025001xhd.hk.gz"
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrtpdcorr_puwnpouf.evt",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("xrtpdcorr","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;
# Task Files Check
    my %par_task = (
		    infile     => "$input/$ArchDir/sw00030025001xpub1po_uf.evt.gz",
		    hdfile     => "$input/$ArchDir/sw00030025001xhd.hk.gz",
		    outfile    => "$output/sw00030025001xpub1po_uf.evt",
		    nframe     => 1850,
		    nevents    => 20,
		    nclip      => 1,
		    nsigma     => 2,
		    thrfile    => "CALDB",
		    biasth     => 183,
		    fittol     => 1.E-8,
		    method     => "SG",
		    bias       => -40., 
		    biasfile   => "CALDB",
		    biasdiff   => 20,
		    chatter    => $chat,
		    clobber    => "$clobber",
		    history    => "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/sw00030025001xpub1po_uf.evt");
	
	
# ftdiff
	$ut->ftdiff("$output/sw00030025001xpub1po_uf.evt",
		    "$input/$ArchDir/ut_xrtpdcorr_puwnpouf.evt");
    }    
    
    $ut->delete();
}
