# Component (mission) name. Developers need not change/delete this.
HD_COMPONENT_NAME	= swift

# Software release version number. Developers need not change/delete this.
HD_COMPONENT_VERS	=

# Perl script(s) to install.
HD_INSTALL_PERL_SCRIPTS	= xrtexpomap

# Help file(s) to install.
HD_INSTALL_HELP		= ${HD_INSTALL_PERL_SCRIPTS}.html

# Parameter file(s) to install.
HD_INSTALL_PFILES	= ${HD_INSTALL_PERL_SCRIPTS}.par
HD_TEST_PERL_SCRIPTS	= ut_${HD_INSTALL_PERL_SCRIPTS}_pc ut_${HD_INSTALL_PERL_SCRIPTS}_wt
include ${HD_STD_MAKEFILE}
