# Component (mission) name. Developers need not change/delete this.
HD_COMPONENT_NAME	= swift

# Software release version number. Developers need not change/delete this.
HD_COMPONENT_VERS	=

# Perl script(s) to install.
HD_INSTALL_PERL_SCRIPTS	= xrtgrblc

# perl libs
HD_INSTALL_PERL_LIBS = libswxrtgrblc.pm

# Help file(s) to install.
HD_INSTALL_HELP		= xrtgrblc.html

# Parameter file(s) to install.
HD_INSTALL_PFILES	= xrtgrblc.par

HD_TEST_PERL_SCRIPTS	= ut_${HD_INSTALL_PERL_SCRIPTS}

include ${HD_STD_MAKEFILE}
