#!/usr/bin/perl
#
#  ut_xrtphascorr
#
#
#
# Changes:
#           0.1.0 - 30/04/2009 - NS First working version
#

use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrtphascorr",
			    utname  => "ut_xrtphascorr",
			    version => "0.1.0",
			    );
    
# Set Parameter
    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
 
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS");
    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_xrtphascorr";
    
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/sw00030925001xpcw2po_uf.evt.gz",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrtphascorr_xpcw2po_uf.evt",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("xrtphascorr","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;
# Task Files Check
    my %par_task = (
		    infile        => "$input/$ArchDir/sw00030925001xpcw2po_uf.evt.gz",
		    outfile       => "$output/sw00030925001xpcw2po_uf.evt",
		    phasconffile  => "$input/$ArchDir/swxphasconf20010101v000.fits",
		    chatter       => $chat,
		    clobber       => "$clobber",
		    history       => "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/sw00030925001xpcw2po_uf.evt");
	
	
# ftdiff
	$ut->ftdiff("$output/sw00030925001xpcw2po_uf.evt",
		    "$input/$ArchDir/ut_xrtphascorr_xpcw2po_uf.evt");
    }    
    
    $ut->delete();
}
