#!/usr/bin/perl
#
#  ut_xrttimetag
#
#
#
# Changes:
#           0.1.0 - 06/08/2004 - RP First working version
#           0.1.1 - 13/01/2005 - BS Deleted 'caldbdir' input parameter
#           0.1.2 - 03/02/2005 - BS Added 'aberration' and 'attinterpol' 
#                                   input parameters
#           0.1.3 - 21/02/2006 - BS Added 'colfile' input parameter
use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrttimetag",
			    utname  => "ut_xrttimetag_lr",
			    version => "0.1.3",
			    );
    
# Set Parameter


    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");

    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);

    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");


# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_xrttimetag";
    
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/sw00073320001xlrwnpouf.evt.gz",
		   "$input/$ArchDir/sw00073320001xhdtc.hk",
		   "$input/$ArchDir/sw00073320001sat.fits.gz"
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrttimetag_lrwnpouf.evt",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("xrttimetag","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;
# Task Files Check
    my %par_task = (

		    infile  => "$input/$ArchDir//sw00073320001xlrwnpouf.evt.gz",
		    outfile  => "$output/sw00073320001xlrwnpouf.evt",
		    hdfile  => "$input/$ArchDir/sw00073320001xhdtc.hk",
		    attfile  => "$input/$ArchDir/sw00073320001sat.fits.gz",
		    usehkkey  => "no",
		    srcra  => 0.,
		    srcdec  => 0.,   
		    ranom  => 0. ,
		    decnom  => 0.,
		    teldef  => "CALDB" ,
		    colfile => "CALDB" ,
		    npixels  => 1850,
		    percent  => 50,
		    chatter    => $chat,
		    clobber    => "$clobber",
		    history    => "yes", 
		    aberration => "no", 
		    attinterpol=> "no" 
		    );

    $ut->runTask(%par_task)
	if($ut->isValid);
    if($ut->isValid)

    {
	
# fverify
	$ut->fverify("$output/sw00073320001xlrwnpouf.evt");
	

	
	
# ftdiff
	$ut->ftdiff("$output//sw00073320001xlrwnpouf.evt",
		    "$input/$ArchDir/ut_xrttimetag_lrwnpouf.evt");
    }    
    
    $ut->delete();
}
