#!/usr/bin/perl
#
#  ut_xrtpcgrade
#
#
#
# Changes:
#           0.1.0 - 04/08/2004 - CS First working version
#           0.1.1 - 05/08/2004 - BS Adapted for xrtpcgrade task
#           0.1.2 - 13/01/2005 - BS Deleted 'caldb' input parameter
#           0.1.3 - 16/03/2005 - BS Added 'hdfile' input parameter 
#           0.1.4 - 10/07/2007 - NS Added 'thrfile' input parameter

use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrtpcgrade",
			    utname  => "ut_xrtpcgrade",
			    version => "0.1.4",
			    );
    
# Set Parameter
    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
    
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_xrtpcgrade";
    
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/sw00073232001xpcwnpouf.evt.gz",
		   "$input/$ArchDir/sw00073232001xhd.hk.gz",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrtpcgradexpcwnpouf.evt",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("xrtpcgrade","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;
# Task Files Check
    my %par_task = (

		    infile     => "$input/$ArchDir/sw00073232001xpcwnpouf.evt.gz",
		    hdfile     => "$input/$ArchDir/sw00073232001xhd.hk.gz",
		    outfile    => "$output/sw00073232001xpcwnpouf.evt",
		    thrfile    => "NONE",
                    gradefile  => "CALDB",
                    split      => -5,
                    ascagrade  => "no",
		    chatter    => $chat,
		    clobber    => "$clobber",
		    history    => "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/sw00073232001xpcwnpouf.evt");
	
	
# ftdiff
	$ut->ftdiff("$output/sw00073232001xpcwnpouf.evt",
		    "$input/$ArchDir/ut_xrtpcgradexpcwnpouf.evt");
    }    
    
    $ut->delete();
}
