#!/usr/bin/perl
#
#  ut_xrtflagpix_wt
#
#
#
# Changes:
#           0.1.0 - 04/08/2004 - CS First working version
#           0.1.1 - 05/08/2004 - BS Adapted for xrtflagpix task
#           0.1.2 - 06/10/2004 - FT Changed badpix and onboardbp CALDB 
#                                   file name
#           0.1.3 - 11/01/2005 - BS Deleted 'caldbdir' input parameter
#           0.1.4 - 10/07/2007 - NS Added 'thrfile' input parameter

use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrtflagpix",
			    utname => "ut_xrtflagpix_wt",
			    version => "0.1.4",
			    );
    
# Set Parameter
    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");

# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_xrtflagpix";
    
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/sw00073213001xwtwnpouf.evt.gz"
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrtflagpix_wtwnpouf.evt","$input/$ArchDir/ut_xrtflagpix_wtwnpoufbp.fits"
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("xrtflagpix","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;
# Task Files Check
    my %par_task = (

		    infile     => "$input/$ArchDir/sw00073213001xwtwnpouf.evt.gz",
		    outfile    => "$output/sw00073213001xwtwnpouf.evt",
		    bpfile     => "CALDB",
		    userbpfile => "NONE",
		    bptable    => "CALDB",
		    thrfile    => "CALDB",
		    outbpfile  => "DEFAULT",
		    maxtemp    => 0.0,
                    overstatus => "yes",
		    chatter    => $chat,
		    clobber    => "$clobber",
		    history    => "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/sw00073213001xwtwnpouf.evt");
	$ut->fverify("$output/sw00073213001xwtwnpoufbp.fits");
	
	
# ftdiff
	$ut->ftdiff("$output/sw00073213001xwtwnpouf.evt",
		    "$input/$ArchDir/ut_xrtflagpix_wtwnpouf.evt");

	$ut->ftdiff("$output/sw00073213001xwtwnpoufbp.fits",
		    "$input/$ArchDir/ut_xrtflagpix_wtwnpoufbp.fits");
    }    
    
    $ut->delete();
}
