#!/usr/bin/perl
#
#  ut_xrtcalcpi_pc
#
#
#
# Changes:
#           0.1.0 - 04/08/2004 - CS First working version
#           0.1.1 - 05/08/2004 - BS Adapted for xrtcalcpi task
#           0.1.2 - 11/12/2005 - BS Deleted caldbdir input parameter
#           0.1.3 - 23/03/2005 - FT Added hdfile input
#           0.1.4 - 06/03/2009 - NS Added new xrtcalcpi input parameters
#           0.1.5 - 21/03/2011 - NS Added new xrtcalcpi input parameters

use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrtcalcpi",
			    utname  => "ut_xrtcalcpi_pc",
			    version => "0.1.5",
			    );
    
# Set Parameter
    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");

# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_xrtcalcpi";
    
    
# Input Files Check
    my @chk_inp = (
		   "$input/$ArchDir/sw00073232001xpcwnpouf.evt.gz",
		   "$input/$ArchDir/sw00073213001xhd.hk.gz",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrtcalcpi_pcwnpouf.evt",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("xrtcalcpi","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;
# Task Files Check

    my %par_task = (

		    infile     => "$input/$ArchDir/sw00073232001xpcwnpouf.evt.gz",
		    outfile    => "$output/sw00073232001xpcwnpouf.evt",
		    hdfile     => "$input/$ArchDir/sw00073232001xhd.hk.gz",
		    gainfile   => "CALDB", 
                    seed       => -1457,
                    randomflag => "no",
                    gainnom    => -99.9,
                    offset     => 0.0,
                    corrtype   => "NOMINAL",
                    userctcorrpar  => "no",
                    alpha1     => 0,
                    alpha2     => 0,
                    ebreak     => 1,
                    userctipar => "no",
                    beta1      => 0,
                    beta2      => 0,
                    ecti       => 1,
		    offsetniter  => 2,
		    savepioffset => "no",
		    chatter    => $chat,
                    savepinom  => "yes",
		    clobber    => "$clobber",
		    history    => "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/sw00073232001xpcwnpouf.evt");
	
	
# ftdiff
	$ut->ftdiff("$output/sw00073232001xpcwnpouf.evt",
		    "$input/$ArchDir/ut_xrtcalcpi_pcwnpouf.evt");
    }    
    
    $ut->delete();
}
