#!/usr/bin/perl
#
#  ut_xrtwtcorr
#
#
#
# Changes:
#           0.1.0 - 10/06/2005 - BS First working version
#           0.1.1 - 09/09/2005 - BS Bug fixed in 'ftdiff' command line
#           0.1.2 - 23/02/2006 -    Added 'colfile' input parameter
#           0.1.3 - 08/11/2006 -    Added 'nframe' and 'biasmode' input parameters
#           0.1.4 - 06/02/2007 -    Added 'biasth' and 'npixels' input parameters
#           0.1.5 - 10/07/2007 - NS Added 'thrfile' input parameter
#
use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrtwtcorr",
			    utname  => "ut_xrtwtcorr",
			    version => "0.1.5",
			    );
    
# Set Parameter
    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");
 
# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS");
    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_xrtwtcorr";
    
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/sw00130088018xwtw2po_uf.evt.gz",
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrtwtcorr_xwtw2po_uf.evt",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("xrtwtcorr","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;
# Task Files Check
    my %par_task = (
		    infile     => "$input/$ArchDir/sw00130088018xwtw2po_uf.evt.gz",
		    outfile    => "$output/sw00130088018xwtw2po_uf.evt",
		    biasdiff   => 20,
		    hdfile     => "$input/$ArchDir/sw00130088018xhd.hk.gz",
		    trfile     => "$input/$ArchDir/sw00130088018xtr.hk.gz",
		    nevents    => 20,
		    nframe     => 1,
		    biasmode   => "SP",
		    thrfile    => "CALDB",
		    biasth     => 200,
		    npixels    => 20,
		    colfile    => "CALDB",
		    chatter    => $chat,
		    clobber    => "$clobber",
		    history    => "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/sw00130088018xwtw2po_uf.evt");
	
	
# ftdiff
	$ut->ftdiff("$output/sw00130088018xwtw2po_uf.evt",
		    "$input/$ArchDir/ut_xrtwtcorr_xwtw2po_uf.evt");
    }    
    
    $ut->delete();
}
