#!/usr/bin/perl
#
#  ut_xrthkproc
#
#
#
# Changes:
#           0.1.0 - 04/08/2004 - CS First working version
#           0.1.1 - 05/08/2004 - BS Adapted for xrthkproc task
#           0.1.2 - 13/01/2005 - BS Deleted 'caldbdir' input parameter
#           0.1.3 - 03/02/2005 - BS Added 'attinterpol' and 'aberration' input
#                                   parameters
#           0.1.4 - 04/07/2005 - BS Added 'srcdetx' and 'srcdety' input parameters
#
use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrthkproc",
			    utname  => "ut_xrthkproc",
			    version => "0.1.4",
			    );
    
# Set Parameter
    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");


# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_xrthkproc";
    
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/sw00073320001xhd.hk.gz","$input/$ArchDir/sw00073320001sat.fits.gz"
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrthkproc.hk",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("xrthkproc","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;
# Task Files Check
    my %par_task = (
		    hdfile  => "$input/$ArchDir/sw00073320001xhd.hk.gz",
		    outfile => "$output/sw00073320001xhdtc.hk",
		    attfile =>"$input/$ArchDir/sw00073320001sat.fits.gz",
                    srcra   => 0.,
                    srcdec  => 0.,
                    ranom   => 0.,
                    decnom  => 0.,
		    srcdetx => 300,
		    srcdety => 300,
                    teldef  => "CALDB",
		    chatter    => $chat,
		    clobber    => "$clobber",
		    history    => "yes", 
                    attinterpol=> "no",
                    aberration => "no"
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/sw00073320001xhdtc.hk");
	
	
# ftdiff
	$ut->ftdiff("$output/sw00073320001xhdtc.hk",
		    "$input/$ArchDir/ut_xrthkproc.hk");
    }    
    
    $ut->delete();
}
