#!/usr/bin/perl
#
#  ut_xrtmkarf_lr
#
#
#
# Changes:
#           0.1.0 - 04/08/2004 - CS First working version
#           0.1.1 - 05/08/2004 - BS Adapted for xrtmkarf task
#           0.1.2 - 13/01/2005 - BS Deleted 'caldbdir' input parameter
#           0.1.3 - 11/02/2005 - BS Replaced 'srcdetx/y' with 'srcx/y'
#           0.1.4 - 17/02/2005 - BS Added 'inarffile' input parameter
#           0.1.5 - 22/06/2010 - NS Added 'extended', 'boxsize', 'offaxis' and 'cleanup' input parameters
#           0.1.6 - 11/06/2015 - NS Added 'expofile' input parameter

use strict;
use ut_xrtobj;

# main
{
# Object Istances
    my $ut = ut_xrtobj->new(
			    name    => "xrtmkarf",
			    utname  => "ut_xrtmkarf_lr",
			    version => "0.1.6",
			    );
    
# Set Parameter
    #$ut->setParam("validate", 0);
    my $input = $ut->getParam("input_dir");
    my $output = $ut->getParam("output_dir") . "/" . $ut->getParam("utname");
    $ut->setParam("output_dir",$output);
    my $chat = $ut->getParam("chatter");
    my $clobber = $ut->getParam("clobber");

# I/O Directory Check
    $ut->checkIODirectory()
        if $ut->isValid;

# Environment check
    my @chk_env = ("LHEASOFT", "HEADAS", "CALDB");

    $ut->checkEnvironment(@chk_env)
        if $ut->isValid;
    
    my $ArchDir="ut_xrtmkarf";
    
    
# Input Files Check
    my @chk_inp = ("$input/$ArchDir/sw00073320001xlrwnposr.pha"
		   );

    $ut->checkExist("Input", @chk_inp)
	if $ut->isValid;
    
# Prototype Check
   my @chk_proto = ("$input/$ArchDir/ut_xrtmkarf_lr.arf",
		    );
    $ut->checkExist("Prototype", @chk_proto)
        if $ut->isValid;

# Executables Files Check
    my @chk_exe = ("xrtmkarf","ftdiff","fverify", "pquery2");
    $ut->checkExecutable(@chk_exe)
        if $ut->isValid;
# Task Files Check
    my %par_task = (
		    
		    outfile    => "$output/sw00073320001xlrwnposr.arf",
		    rmffile    => "CALDB",
		    inarffile  => "CALDB",
		    expofile   => "NONE",
		    mirfile    => "CALDB",
		    transmfile => "CALDB",
		    psffile    => "CALDB",
		    psfflag    => "yes",  
		    vigfile    => "CALDB",
		    phafile    => "$input/$ArchDir/sw00073320001xlrwnposr.pha",
		    srcx       => 300,   
		    srcy       => 300, 
 		    offaxis    => -99,
		    extended   => "no",
		    boxsize    => 10,
		    cleanup    => "yes",
		    chatter    => $chat,
		    clobber    => "$clobber",
		    history    => "yes" 
		    );

    $ut->runTask(%par_task)
	if $ut->isValid;
    if($ut->isValid)
    {
	
# fverify
	$ut->fverify("$output/sw00073320001xlrwnposr.arf");
	
	
# ftdiff
	$ut->ftdiff("$output/sw00073320001xlrwnposr.arf",
		    "$input/$ArchDir/ut_xrtmkarf_lr.arf");
    }    
    
    $ut->delete();
}
